name = "Fabian Almanza"
rol = "Frontend Developer"
email = "fabian.almanza@correo.uis.edu.co"
phone = "+57 (302) 303-5359"
birthday = "Enero 25, 1995"
location = "Bucaramanga, Santander, COL"
avatar = "./config/assets/avatars/my-avatar.png"
username = "fabianalmanza" # <-- github user name

presentation = """
"¡Hola! Soy Fabián, un ingeniero de petróleos apasionado por el mundo del desarrollo de software y la creación de aplicaciones web innovadoras
Mi objetivo es aprovechar mis conocimientos técnicos y experiencia en ingeniería  para contribuir al campo de la ingeniería de software, especialmente en el ámbito del frontend.
"""
