name = "Om Ambadas Bade"
rol = "Student at Sanjivani COE"
email = "ombade364@gmail.com"
phone = "+91 9022157947"
birthday = "November 21, 2003"
location = "Ahmednagar , Maharastra ,India"
avatar = "./config/assets/avatars/my-avatar.png"
username = "ombade" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d199666.5651251294!2d-121.58334177520186!3d38.56165006739519!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x809ac672b28397f9%3A0x921f6aaa74197fdb!2sSacramento%2C%20CA%2C%20USA!5e0!3m2!1sen!2sbd!4v1647608789441!5m2!1sen!2sbd" 
presentation = ""Hello Om Bade"
ğŸ‘¨â€ğŸ’» ğŸ“ Computer Engineering Student | Sanjivani College, Maharashtra, India ğŸŒ Passionate about machine learning, computer vision, and AI technologies. Over a year of immersive experience in data science and machine learning. Proven knack for unraveling complex problems, driving innovation, and crafting predictive models. Committed to perpetual growth, adept at assimilating emerging technologies. "Algorithmic artist, painting vibrant pictures with lines of code." Let's connect and ignite inspiration! ğŸš€ #TechEnthusiast
I integrate cutting-edge technologies such as Data Science, AI, and ML into my designs. With a track record of collaborating with diverse clients, I excel in bringing brand identities to life through innovative solutions.
My job is to build your website so that it is functional and user-friendly but at the same time attractive. Moreover, I add personal touch to your product and make sure that is eye-catching and easy to use. My aim is to bring across your message and identity in the most creative way. I created web design for many famous brand companies.
"""
