# https://ionic.io/ionicons
# <ion-icon name="[[name]]"></ion-icon>
# name = "https://example.com/"

# logo-facebook = "https://facebook.com/"
logo-instagram = "https://www.instagram.com/_shahrukh.mansuri_/?__a=1"
logo-linkedin = "https://www.linkedin.com/in/shahrukh1426/"
logo-github = "https://github.com/shahrukh1426"
# logo-dribbble = "https://dribbble.com/"
# logo-figma = "figma.com/"
# logo-youtube = "https://youtube.com/"
# logo-reddit = "https://www.reddit.com/"
# logo-discord = "https://discord.com/"
# logo-pinterest = "https://www.pinterest.com/"
